FROM scratch
ADD centos-7-docker.tar.xz /

ADD ./apache-tomcat-8.5.23.tar.gz  /usr/local/
ADD ./jdk-8u151-linux-x64.tar.gz  /usr/local/
COPY ./StarTrek.war                /usr/local/apache-tomcat-8.5.23/webapps

ENV JAVA_HOME /usr/local/jdk1.8.0_151
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $JAVA_HOME/bin:$PATH
ENV CATALINA_HOME /usr/local/apache-tomcat-8.5.23
ENV PATH $PATH:$CATALINA_HOME/bin

LABEL org.label-schema.schema-version = "1.0" \
    org.label-schema.name="CentOS Base Image" \
    org.label-schema.vendor="CentOS" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20180531"

CMD ["/bin/bash"]