---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-n1
  template:
    metadata:
      labels:
        app: zookeeper-n1
    spec:
      hostname: zookeeper-n1
      volumes:
        - name: zookeeper-data
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-data-n1
        - name: zookeeper-logs
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-logs-n1
      dnsPolicy: ClusterFirst
      containers:
      - name: zookeeper-n1
        image: zookeeper
        imagePullPolicy: Always
        volumeMounts:
        - name: zookeeper-data
          readOnly: false
          mountPath: "/data/zookeeper-data"
        - name: zookeeper-logs
          readOnly: false
          mountPath: "/data/zookeeper-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: server.1=zookeeper-n1:2888:3888 server.2=zookeeper-n2:2888:3888 server.3=zookeeper-n3:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zookeeper-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zookeeper-logs'  

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-n2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-n2
  template:
    metadata:
      labels:
        app: zookeeper-n2
    spec:
      hostname: zookeeper-n2
      volumes:
        - name: zookeeper-data
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-data-n2
        - name: zookeeper-logs
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-logs-n2
      dnsPolicy: ClusterFirst
      containers:
      - name: zookeeper-n2
        image: zookeeper
        imagePullPolicy: Always
        volumeMounts:
        - name: zookeeper-data
          readOnly: false
          mountPath: "/data/zookeeper-data"
        - name: zookeeper-logs
          readOnly: false
          mountPath: "/data/zookeeper-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: "2"
        - name: ZOO_SERVERS
          value: server.1=zookeeper-n1:2888:3888 server.2=zookeeper-n2:2888:3888 server.3=zookeeper-n3:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zookeeper-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zookeeper-logs'  

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-n3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-n3
  template:
    metadata:
      labels:
        app: zookeeper-n3
    spec:
      hostname: zookeeper-n3
      volumes:
        - name: zookeeper-data
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-data-n3
        - name: zookeeper-logs
          hostPath: 
            path: /data/zookeeper-cluster/zookeeper-logs-n3
      dnsPolicy: ClusterFirst
      containers:
      - name: zookeeper-n3
        image: zookeeper
        imagePullPolicy: Always
        volumeMounts:
        - name: zookeeper-data
          readOnly: false
          mountPath: "/data/zookeeper-data"
        - name: zookeeper-logs
          readOnly: false
          mountPath: "/data/zookeeper-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: "3"
        - name: ZOO_SERVERS
          value: server.1=zookeeper-n1:2888:3888 server.2=zookeeper-n2:2888:3888 server.3=zookeeper-n3:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zookeeper-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zookeeper-logs' 

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-n1
  name: zookeeper-n1
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    name: client
  - port: 2888
    protocol: TCP
    targetPort: 2888
    name: leader
  - port: 3888
    protocol: TCP
    targetPort: 3888
    name: leader-election
  selector:
    app: zookeeper-n1
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-n2
  name: zookeeper-n2
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    name: client
  - port: 2888
    protocol: TCP
    targetPort: 2888
    name: leader
  - port: 3888
    protocol: TCP
    targetPort: 3888
    name: leader-election
  selector:
    app: zookeeper-n2
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-n3
  name: zookeeper-n3
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    name: client
  - port: 2888
    protocol: TCP
    targetPort: 2888
    name: leader
  - port: 3888
    protocol: TCP
    targetPort: 3888
    name: leader-election
  selector:
    app: zookeeper-n3
  sessionAffinity: None
  type: ClusterIP
